### ISSUE TITLE
A small correction

### ISSUE THREAD

**Issue by Bluhme1** [nickknissen/hass-monta#20]
### System Health details

No details

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi @nickknissen 

Thank you for your latest version. I think the newly added sensor "Last_meter_readings_kwh" shows the total kWh from the charger. My number is 569,244 kWh and thus far too big for the kWh of a single charge 
Consequently I think it can be used as input to Utility_Meter helpers (Hour, Day, Month, Year). So the newly created sensor is much appreciated.
/Lars

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
No logs
```

**Comment by nickknissen** [comment]
Thank you for bringing this to my attention! I appreciate your feedback.

I understand your concern regarding the `sensor.charger_last_meter_reading_kwh` sensor displaying a total kWh value rather than the kWh from a single charge. 
After reviewing the API data from my charge, it seems that there might be a discrepancy in the way Monta calculates the value.

I've [reached out](https://docs.public-api.monta.com/discuss/64fae7ecc99013145c9a4137) to the Monta support team, and they also indicated that "lastMeterReadingKwh" represents the kWh from the last charge, not the totalConsumptionKwh which you were looking for.

But if you are `569,244` kwh in the sensor there might be a bug within the Monta API where it returns the total kWh for some users and last charge kwh for others.

I will let Monta known about the issue.
